### ISSUE TITLE
json to cereal - error

### ISSUE THREAD

**Issue by samsgates** [patrikhuber/eos#48]
when i run the below command, error message triggered like rapidjsonexception:
./json-to-cereal-binary -i /Users/sam/Documents/MATLAB/bfm_small.json -t model -o converted_model.bin

Error : 
libc++abi.dylib: terminating with uncaught exception of type cereal::RapidJSONException: rapidjson internal assertion failure: flags_ & kIntFlag

Debug Result:
error message triggered from the below line
input_archive(morphable_model);

code :

if (file_type == "model")
	{
		morphablemodel::MorphableModel morphable_model;
		std::ifstream file(jsonfile.string());
		cereal::JSONInputArchive input_archive(file);
		**input_archive(morphable_model);**
		morphablemodel::save_model(morphable_model, outputfile.string());
	}

**Comment by samsgates** [comment]
i have tried re download the complete project and run it agin, this time code is not compiled because of the below error

cereal.hpp:829:9: Static_assert failed "cereal could not find any input serialization functions for the provided type and archive combination. \n\n Types must either have a serialize function, load/save pair, or load_minimal/save_minimal pair (you may not mix these). \n Serialize functions generally have the following signature: \n\n template<class Archive> \n   void serialize(Archive & ar) \n   { \n     ar( member1, member2, member3 ); \n   } \n\n "

Note:  i used xcode for build this project

Find the attached screenshot for reference
![attachement](https://cloud.githubusercontent.com/assets/4558944/17582349/d2f617a0-5fc8-11e6-8b76-7ae7543f1d2b.png)

**Comment by samsgates** [comment]
problem in "!= 0" (if i replace 0 to any other number ,it working fine). 
right now i have commented that "static_assert" line, and working fine, i can build successfully. 

but problem 1 still existed:
Error : 
libc++abi.dylib: terminating with uncaught exception of type cereal::RapidJSONException: rapidjson internal assertion failure: flags_ & kIntFlag

**Comment by patrikhuber** [comment]
> cereal could not find any input serialization functions for the provided type and archive combination

The log should show for which combination of types it's not finding a serialisation function. Can you have a look?

And you shouldn't just replace that zero with something else, nothing will work anyway if you do that.

I don't have a Mac, so I don't know if any of this could be related to problems on Mac. Do you have means to build in a Linux/Windows VM? (Linux is probably easier)

When I committed that code it was definitely working, so it should work, but of course I can't rule out a problem. I won't have time to test it now though, earliest will be mid/end of next week.

**Comment by samsgates** [comment]
Error : 
libc++abi.dylib: terminating with uncaught exception of type cereal::RapidJSONException: rapidjson internal assertion failure: flags_ & kIntFlag

This error looks like integer value is bigger than limit (int variable should be Uint or Uint64). 
any way i check with other system

**Comment by patrikhuber** [comment]
Did you fix this? Was it a problem with your setup? Or Mac OS?

**Comment by samsgates** [comment]
i don't have Windows PC to validate this error, but problem still existed in Mac system. 
right now i used PCAmodel class to generate binary file.
